# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/calot/Projekty/workspace_cpp/DCL/ObjectRecognition

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/calot/Projekty/workspace_cpp/DCL/ObjectRecognition

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"components\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/calot/Projekty/workspace_cpp/DCL/ObjectRecognition/CMakeFiles /home/calot/Projekty/workspace_cpp/DCL/ObjectRecognition/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/calot/Projekty/workspace_cpp/DCL/ObjectRecognition/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ConvolutionFilter

# Build rule for target.
ConvolutionFilter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ConvolutionFilter
.PHONY : ConvolutionFilter

# fast build rule for target.
ConvolutionFilter/fast:
	$(MAKE) -f src/Components/ConvolutionFilter/CMakeFiles/ConvolutionFilter.dir/build.make src/Components/ConvolutionFilter/CMakeFiles/ConvolutionFilter.dir/build
.PHONY : ConvolutionFilter/fast

#=============================================================================
# Target rules for targets named ContrastManipulation

# Build rule for target.
ContrastManipulation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContrastManipulation
.PHONY : ContrastManipulation

# fast build rule for target.
ContrastManipulation/fast:
	$(MAKE) -f src/Components/ContrastManipulation/CMakeFiles/ContrastManipulation.dir/build.make src/Components/ContrastManipulation/CMakeFiles/ContrastManipulation.dir/build
.PHONY : ContrastManipulation/fast

#=============================================================================
# Target rules for targets named MedianBlurFilter

# Build rule for target.
MedianBlurFilter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MedianBlurFilter
.PHONY : MedianBlurFilter

# fast build rule for target.
MedianBlurFilter/fast:
	$(MAKE) -f src/Components/MedianBlurFilter/CMakeFiles/MedianBlurFilter.dir/build.make src/Components/MedianBlurFilter/CMakeFiles/MedianBlurFilter.dir/build
.PHONY : MedianBlurFilter/fast

#=============================================================================
# Target rules for targets named Thresholding

# Build rule for target.
Thresholding: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Thresholding
.PHONY : Thresholding

# fast build rule for target.
Thresholding/fast:
	$(MAKE) -f src/Components/Thresholding/CMakeFiles/Thresholding.dir/build.make src/Components/Thresholding/CMakeFiles/Thresholding.dir/build
.PHONY : Thresholding/fast

#=============================================================================
# Target rules for targets named LogicFilter

# Build rule for target.
LogicFilter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LogicFilter
.PHONY : LogicFilter

# fast build rule for target.
LogicFilter/fast:
	$(MAKE) -f src/Components/LogicFilter/CMakeFiles/LogicFilter.dir/build.make src/Components/LogicFilter/CMakeFiles/LogicFilter.dir/build
.PHONY : LogicFilter/fast

#=============================================================================
# Target rules for targets named RankFiltering

# Build rule for target.
RankFiltering: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RankFiltering
.PHONY : RankFiltering

# fast build rule for target.
RankFiltering/fast:
	$(MAKE) -f src/Components/RankFiltering/CMakeFiles/RankFiltering.dir/build.make src/Components/RankFiltering/CMakeFiles/RankFiltering.dir/build
.PHONY : RankFiltering/fast

#=============================================================================
# Target rules for targets named NewestImage

# Build rule for target.
NewestImage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NewestImage
.PHONY : NewestImage

# fast build rule for target.
NewestImage/fast:
	$(MAKE) -f src/Components/NewestImage/CMakeFiles/NewestImage.dir/build.make src/Components/NewestImage/CMakeFiles/NewestImage.dir/build
.PHONY : NewestImage/fast

#=============================================================================
# Target rules for targets named BrightnessManipulation

# Build rule for target.
BrightnessManipulation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BrightnessManipulation
.PHONY : BrightnessManipulation

# fast build rule for target.
BrightnessManipulation/fast:
	$(MAKE) -f src/Components/BrightnessManipulation/CMakeFiles/BrightnessManipulation.dir/build.make src/Components/BrightnessManipulation/CMakeFiles/BrightnessManipulation.dir/build
.PHONY : BrightnessManipulation/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ConvolutionFilter"
	@echo "... ContrastManipulation"
	@echo "... MedianBlurFilter"
	@echo "... Thresholding"
	@echo "... LogicFilter"
	@echo "... RankFiltering"
	@echo "... NewestImage"
	@echo "... BrightnessManipulation"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

